name: vidur
channels:
  - conda-forge
dependencies:
  - python=3.10
  - setuptools
  - pip
  - numpy        # Add numpy back in
  - plotly_express
  - jupyterlab
  - matplotlib
  - scikit-learn
  - make         # Dev dependencies start here
  - black
  - isort
  - flake8
  - autopep8

